name: Test, build, and publish the application

on:
  push:
    branches: [main]

jobs:
  test-build-and-publish:
    name: Test, build, and publish the application
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_GITHUB_ACTIONS }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Check requirements.txt is up to date
        run: |
          source venv/bin/activate
          pip install .[all]
          pip uninstall -y hello-world-api-py
          pip freeze > requirements.txt
          git diff --quiet
          if [ ! $? -eq 0 ]; then
            echo "pip freeze caused file changes, failing!"
            exit 1
          fi

      - name: Check style
        run: |
          source venv/bin/activate
          make style

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      - name: Build application image
        run: |
          bin/docker-build

      - name: Checkout tdg5/github-action-pack
        uses: actions/checkout@v4
        with:
          path: .github/actions/tdg5/github-action-pack
          ref: v0.0.4
          repository: tdg5/github-action-pack

      - name: Increment version
        uses: ./.github/actions/tdg5/github-action-pack/packages/increment-version-file-action/src
        with:
          authorEmail: dannyguinther+spamburglar@gmail.com
          authorName: Spamburglar
          commitMessage: "[skip actions] Increment version for next development cycle"
          versionFilePath: VERSION
          versionFormat: python

      - name: Publish application to image repository
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_USERNAME: __token__
        run: |
          source venv/bin/activate
          echo "TODO"

      # Add the tag after publishing the application so it is more likely that we
      # end up with an application without a tag than a tag without an application.
      - name: Create and push tag for published version
        run: |
          VERSION="$(git show HEAD~1:VERSION)"
          TAG_NAME="v${VERSION}"
          git tag "$TAG_NAME" HEAD~1
          git push origin "$TAG_NAME"
